export const types = {
  // Common
  SET_FORM_LODER: "SET_FORM_LODER",
  SET_FORM_ERRORS: "SET_FORM_ERRORS",
  SET_MESSAGE: "SET_MESSAGE",

  // Auth
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
}
